module.exports = [
	"assets/images/black_dragon_bullet.png",
	"assets/images/clouds_first.png",
	"assets/images/clouds_foreground.png",
	"assets/images/enemy_bullet.png",
	"assets/images/dragon_explosion.png",
	"assets/images/green_dragon.png",
	"assets/images/green_dragon_bullet.PNG",
	"assets/images/island_1.png",
	"assets/images/islands.png",
	"assets/images/light_ship.png",
	"assets/images/red_dragon_bullet.png",
	"assets/images/sea_background_1.png",
	"assets/images/sea_background_2.png",
	"assets/images/sea_background_3.png",
	"assets/images/red_dragon.png",
];